name: 'orderly'
version: '1.0.0'
config-version: 2

# Medallion Architecture - Bronze/Silver/Gold data pipeline
profile: 'orderly'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Medallion tier configurations
models:
  orderly:
    bronze:
      # Raw data - materialized as views for zero-copy access
      +materialized: view
      +schema: bronze
      +docs:
        node_color: "#8B4513"  # Bronze color
    silver:
      # Clean, conformed data - materialized as tables for performance
      +materialized: table
      +schema: silver
      +docs:
        node_color: "#C0C0C0"  # Silver color
    gold:
      # Curated marts - materialized as tables with indexes
      +materialized: table
      +schema: gold
      +docs:
        node_color: "#FFD700"  # Gold color

seeds:
  orderly:
    +schema: seeds

# Medallion architecture variables
vars:
  database_path: "../data/orderly.duckdb"
  bronze_path: "../data/bronze"
  silver_path: "../data/silver"
  gold_path: "../data/gold"
  
  # Data quality thresholds
  price_anomaly_threshold: 3.0  # Standard deviations
  fuzzy_match_threshold: 0.7    # Similarity score
  unit_standardisation: true    # Enable unit conversion
