name: 'orderly'
version: '1.0.0'
config-version: 2

# Medallion Architecture - Bronze/Silver/Gold data pipeline
profile: 'orderly'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Create schemas on startup
on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS bronze;"
  - "CREATE SCHEMA IF NOT EXISTS silver;"
  - "CREATE SCHEMA IF NOT EXISTS gold;"

# Medallion tier configurations
models:
  orderly:
    bronze:
      # Raw data - materialized as tables for Bronze layer
      +materialized: table
      +schema: bronze
      +docs:
        node_color: "#8B4513"  # Bronze color
    silver:
      # Clean, conformed data - materialized as tables for performance
      +materialized: table
      +schema: silver
      +docs:
        node_color: "#C0C0C0"  # Silver color
    gold:
      # Curated marts - materialized as tables with indexes
      +materialized: table
      +schema: gold
      +docs:
        node_color: "#FFD700"  # Gold color

seeds:
  orderly:
    +schema: seeds
    canonical_brands:
      +docs:
        node_color: "#2E8B57"  # Sea green for master data
    canonical_sku_catalog:
      +docs:
        node_color: "#2E8B57"  # Sea green for master data

# Project variables
vars:
  source_data_path: "data/source"