orderly:
  outputs:
    dev:
      type: duckdb
      path: '../data/orderly.duckdb'
      schema: main
      threads: 4
      keepalives_idle: 0
      search_path: "main"
      
    prod:
      type: duckdb
      path: '../data/orderly_prod.duckdb'
      schema: main
      threads: 8
      keepalives_idle: 0
      search_path: "main"
      
  target: dev
