version: 2

models:
  - name: stg_orders
    description: "Staging orders with clean, validated data - Silver layer entry point"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - not_null
      - name: line_number
        description: "Line number within order"
        tests:
          - not_null
      - name: sku_id
        description: "Product SKU identifier"
        tests:
          - not_null
      - name: item_description_original
        description: "Original item description from source"
      - name: item_description_cleaned
        description: "Cleaned item description (HTML unescaped, tags stripped, lowercased)"
      - name: quantity
        description: "Quantity ordered"
      - name: unit_price
        description: "Unit price"
      - name: currency
        description: "Currency code"
      - name: vendor_brand
        description: "Vendor brand name from orders data"
      - name: cost_centre_id
        description: "Cost centre identifier"
      - name: country_code
        description: "Country code"
      - name: requisitioner
        description: "Person who made the requisition"
      - name: approval_status
        description: "Approval status of the order"
      - name: delivery_date
        description: "Expected delivery date"
      - name: order_date
        description: "Order date"
        tests:
          - not_null
      - name: source_filename
        description: "Source data filename"
        tests:
          - not_null
      - name: created_timestamp
        description: "Record creation timestamp"
        tests:
          - not_null
      - name: non_product_hint
        description: "Flag indicating likely non-product line items (tax, shipping, fees)"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: line_uid
        description: "Unique line identifier (deterministic hash)"
        tests:
          - not_null
          - unique
    tests:
      - assert_rowcount

  - name: silver_cost_centres
    description: "Silver cost centres - clean reference data"
    columns:
      - name: cost_centre_id
        description: "Unique cost centre identifier"
        tests:
          - not_null
          - unique
      - name: cost_centre_name
        description: "Cost centre name"
        tests:
          - not_null
      - name: country_code
        description: "ISO country code"
        tests:
          - not_null

  - name: silver_exchange_rates
    description: "Silver exchange rates - clean reference data"
    columns:
      - name: date
        description: "Exchange rate date"
        tests:
          - not_null
      - name: from_currency
        description: "Source currency code"
        tests:
          - not_null
      - name: to_currency
        description: "Target currency code"
        tests:
          - not_null
      - name: exchange_rate
        description: "Exchange rate value"
        tests:
          - not_null

  - name: silver_vendor_master
    description: "Silver vendor master - clean reference data"
    columns:
      - name: vendor_id
        description: "Unique vendor identifier"
        tests:
          - not_null
          - unique
      - name: vendor_name
        description: "Vendor company name"
        tests:
          - not_null

  - name: silver_orders_fuzz_scores
    description: "Fuzzy matching scores between order descriptions and seed SKU names"
    columns:
      - name: line_uid
        description: "Unique identifier for each order line"
        tests:
          - not_null
      - name: sku_id
        description: "Product SKU identifier"
        tests:
          - not_null
      - name: fuzz_score
        description: "Fuzzy matching score (0-1) between order description and seed name"
        tests:
          - not_null

  - name: silver_orders_with_flags
    description: "Orders with quality flags for SKU lookup and name matching issues"
    columns:
      - name: line_uid
        description: "Unique identifier for each order line"
        tests:
          - not_null
          - unique
      - name: sku_id
        description: "Product SKU identifier"
        tests:
          - not_null
      - name: flag_missing_in_seed
        description: "True if SKU appears in orders but not in seed"
        tests:
          - not_null
      - name: flag_name_mismatch
        description: "True if fuzzy match score < 0.8"
        tests:
          - not_null
      - name: has_quality_issues
        description: "True if any quality flags are raised"
        tests:
          - not_null

  - name: silver_orders_valid
    description: "Clean, valid orders (quality issues filtered out)"
    columns:
      - name: line_uid
        description: "Unique identifier for each order line"
        tests:
          - not_null
          - unique
      - name: order_id
        description: "Order identifier"
        tests:
          - not_null
      - name: sku_id
        description: "Product SKU identifier"
        tests:
          - not_null

  - name: silver_orders_exceptions
    description: "Orders with quality issues for monitoring and analysis"
    columns:
      - name: line_uid
        description: "Unique identifier for each order line"
        tests:
          - not_null
      - name: exception_type
        description: "Type of quality exception (SKU_NOT_IN_SEED, NAME_MISMATCH, OTHER)"
        tests:
          - not_null
          - accepted_values:
              values: ['SKU_NOT_IN_SEED', 'NAME_MISMATCH', 'OTHER']
