version: 2

models:
  - name: stg_orders
    description: "Staging orders with clean, validated data - Silver layer entry point"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - not_null
      - name: line_number
        description: "Line number within order"
        tests:
          - not_null
      - name: sku_id
        description: "Product SKU identifier"
        tests:
          - not_null
      - name: item_description_original
        description: "Original item description from source"
      - name: item_description_cleaned
        description: "Cleaned item description (HTML unescaped, tags stripped, lowercased)"
      - name: quantity
        description: "Quantity ordered"
      - name: unit_price
        description: "Unit price"
      - name: currency
        description: "Currency code"
      - name: vendor_brand
        description: "Vendor brand name from orders data"
      - name: cost_centre_id
        description: "Cost centre identifier"
      - name: country_code
        description: "Country code"
      - name: requisitioner
        description: "Person who made the requisition"
      - name: approval_status
        description: "Approval status of the order"
      - name: delivery_date
        description: "Expected delivery date"
      - name: order_date
        description: "Order date"
        tests:
          - not_null
      - name: source_filename
        description: "Source data filename"
        tests:
          - not_null
      - name: created_timestamp
        description: "Record creation timestamp"
        tests:
          - not_null
      - name: non_product_hint
        description: "Flag indicating likely non-product line items (tax, shipping, fees)"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: line_uid
        description: "Unique line identifier (deterministic hash)"
        tests:
          - not_null
          - unique
    tests:
      - assert_rowcount

  - name: stg_line_items
    description: "Staged line items with basic type casting - Silver layer entry point"
    
  - name: stg_product_skus
    description: "Staged product SKUs with standardised fields - Silver layer"
    
  - name: stg_vendor_master  
    description: "Staged vendor master with normalised names - Silver layer"
    
  - name: int_units_standardised
    description: "Intermediate model with standardised units and sizes"
    
  - name: int_vendors_mapped
    description: "Intermediate model with vendor alias resolution"
    
  - name: int_skus_matched
    description: "Intermediate model with fuzzy SKU matching results"
    
  - name: int_prices_validated
    description: "Intermediate model with price quality validation"
