version: 2

models:
  - name: silver_cost_centres
    description: "Silver cost centres - clean reference data"
    columns:
      - name: cost_centre_id
        description: "Unique cost centre identifier"
        tests:
          - not_null
          - unique
      - name: cost_centre_name
        description: "Cost centre name"
        tests:
          - not_null
      - name: country_code
        description: "ISO country code"
        tests:
          - not_null

  - name: silver_exchange_rates
    description: "Silver exchange rates - direct passthrough from staging layer"
    columns:
      - name: date
        description: "Exchange rate date"
        tests:
          - not_null
      - name: from_currency
        description: "Source currency code (always USD)"
        tests:
          - not_null
          - accepted_values:
              values: ['USD']
      - name: to_currency
        description: "Target currency code (always AUD)"
        tests:
          - not_null
          - accepted_values:
              values: ['AUD']
      - name: exchange_rate
        description: "USD to AUD exchange rate value"
        tests:
          - not_null
      - name: rate_source
        description: |
          Source methodology for the exchange rate:
          - **SOURCE**: Direct USD->AUD rate from raw data (highest confidence)
          - **CALCULATED**: USD->AUD calculated by inverting AUD->USD rate (1/rate)
          - **INTERPOLATED**: Linear interpolation between surrounding known rates
          - **FORWARD_FILLED**: Forward fill used when only historical data available
        tests:
          - not_null
          - accepted_values:
              values: ['SOURCE', 'CALCULATED', 'INTERPOLATED', 'FORWARD_FILLED']

  - name: silver_vendor_master
    description: "Silver vendor master - clean reference data"
    columns:
      - name: vendor_id
        description: "Unique vendor identifier"
        tests:
          - not_null
          - unique
      - name: vendor_name
        description: "Vendor company name"
        tests:
          - not_null

  - name: silver_orders_valid
    description: "Clean, valid orders (SKU, name, and vendor quality issues filtered out)"
    columns:
      - name: line_uid
        description: "Unique identifier for each order line"
        tests:
          - not_null
          - unique
      - name: order_id
        description: "Order identifier"
        tests:
          - not_null
      - name: sku_id
        description: "Product SKU identifier"
        tests:
          - not_null
      - name: cost_centre_id
        description: "Cost centre identifier (FK to silver_cost_centres)"
        tests:
          - not_null
          - relationships:
              to: ref('silver_cost_centres')
              field: cost_centre_id
      - name: matched_vendor_id
        description: "Matched vendor ID from vendor master (high confidence matches only)"
        tests:
          - relationships:
              to: ref('silver_vendor_master')
              field: vendor_id
      - name: matched_vendor_name
        description: "Matched vendor name from vendor master (high confidence matches only)"
      - name: vendor_fuzz_score
        description: "Vendor fuzzy matching score (all records have score > 0.8 or null)"
        tests:
          - not_null

  - name: silver_orders_exceptions
    description: "Orders with data quality issues for monitoring and analysis (excludes non-product items)"
    columns:
      - name: line_uid
        description: "Unique identifier for each order line"
        tests:
          - not_null
      - name: order_id
        description: "Order identifier"
        tests:
          - not_null
      - name: cost_centre_id
        description: "Cost centre identifier (FK to silver_cost_centres)"
        tests:
          - not_null
          - relationships:
              to: ref('silver_cost_centres')
              field: cost_centre_id
      - name: flag_missing_in_seed
        description: "True if SKU missing from seed"
        tests:
          - not_null
      - name: flag_name_mismatch
        description: "True if SKU name fuzzy match score < 0.8"
        tests:
          - not_null
      - name: flag_vendor_mismatch
        description: "True if vendor brand has no good match in vendor master"
        tests:
          - not_null
      - name: vendor_brand_original
        description: "Original vendor brand from order"
      - name: matched_vendor_id
        description: "Matched vendor ID (may be null for exceptions)"
        tests:
          - relationships:
              to: ref('silver_vendor_master')
              field: vendor_id
      - name: matched_vendor_name
        description: "Matched vendor name (may be null for exceptions)"
      - name: vendor_fuzz_score
        description: "Vendor fuzzy matching score"
      - name: exception_type
        description: "Type of quality exception (SKU_NOT_IN_SEED, NAME_MISMATCH, VENDOR_MISMATCH, OTHER)"
        tests:
          - not_null
          - accepted_values:
              values: ['SKU_NOT_IN_SEED', 'NAME_MISMATCH', 'VENDOR_MISMATCH', 'OTHER']

  - name: silver_orders_nonproduct
    description: "Orders identified as non-product items (services, fees, taxes, etc.)"
    columns:
      - name: line_uid
        description: "Unique identifier for each order line"
        tests:
          - not_null
      - name: order_id
        description: "Order identifier"
        tests:
          - not_null
      - name: line_number
        description: "Line number within order"
        tests:
          - not_null
      - name: cost_centre_id
        description: "Cost centre identifier (FK to silver_cost_centres)"
        tests:
          - not_null
          - relationships:
              to: ref('silver_cost_centres')
              field: cost_centre_id
      - name: item_description_original
        description: "Original item description from source"
      - name: item_description_cleaned
        description: "Cleaned item description"
      - name: non_product_hint
        description: "Flag indicating non-product line items"
        tests:
          - not_null
          - accepted_values:
              values: [true]
      - name: record_type
        description: "Record classification type"
        tests:
          - not_null
          - accepted_values:
              values: ['NON_PRODUCT']

  - name: silver_export
    description: "Export trigger for silver layer data - exports all silver models to CSV files in dev environment"
    columns:
      - name: status
        description: "Export completion status"
        tests:
          - not_null
      - name: exported_at
        description: "Timestamp when export was completed"
        tests:
          - not_null
      - name: environment
        description: "dbt target environment"
        tests:
          - not_null
      - name: export_status
        description: "Details about the export operation"
        tests:
          - not_null
