version: 2

models:
  - name: dim_date
    description: "Date dimension with comprehensive temporal attributes and exchange rates"
    columns:
      - name: date_key
        description: "Primary key in YYYYMMDD format"
        tests:
          - unique
          - not_null
      - name: date_actual
        description: "Actual calendar date"
        tests:
          - not_null
      - name: year
        description: "Calendar year"
      - name: quarter
        description: "Calendar quarter (1-4)"
      - name: month
        description: "Calendar month (1-12)"
      - name: fiscal_year
        description: "Fiscal year (July-June)"
      - name: usd_to_aud
        description: "USD to AUD exchange rate for the date"
        
  - name: dim_cost_centre
    description: "Cost centre dimension with organizational hierarchy and geographic attributes"
    columns:
      - name: cost_centre_key
        description: "Surrogate key (MD5 hash of cost_centre_id)"
        tests:
          - unique
          - not_null
      - name: cost_centre_id
        description: "Business key for cost centre"
        tests:
          - unique
          - not_null
      - name: cost_centre_name
        description: "Display name of the cost centre"
      - name: country_code
        description: "ISO country code (AU/US)"
      - name: region
        description: "Geographic region grouping"
        
  - name: dim_vendor
    description: "Vendor dimension with categorization and tier classification"
    columns:
      - name: vendor_key
        description: "Surrogate key (MD5 hash of vendor_id)"
        tests:
          - unique
          - not_null
      - name: vendor_id
        description: "Business key for vendor"
        tests:
          - unique
          - not_null
      - name: vendor_name
        description: "Vendor display name"
      - name: vendor_category
        description: "Derived vendor category based on name patterns"
      - name: vendor_tier
        description: "Vendor tier (Preferred/Standard)"
        
  - name: dim_product
    description: "Product dimension with SKU categorization and brand classification"
    columns:
      - name: product_key
        description: "Surrogate key (MD5 hash of sku_id)"
        tests:
          - unique
          - not_null
      - name: sku_id
        description: "Business key for product SKU"
        tests:
          - unique
          - not_null
      - name: canonical_name
        description: "Standardized product name"
      - name: product_category
        description: "Primary product category (Keyboards, Monitors, etc.)"
      - name: product_subcategory
        description: "Secondary categorization (Wireless, 4K, etc.)"
      - name: product_brand
        description: "Extracted brand name"
      - name: source_type
        description: "Source of the SKU record (approved_seed, auto_ref, auto_discovered)"
      - name: is_approved
        description: "Whether the SKU comes from approved seed data"
        
  - name: fct_order_line
    description: "Core transactional fact for order analysis - Gold layer"
    columns:
      - name: order_line_key
        description: "Surrogate key for order line"
        tests:
          - unique
          - not_null
      - name: date_key
        description: "Order date key (FK to dim_date)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: delivery_date_key
        description: "Delivery date key (FK to dim_date)"
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: cost_centre_key
        description: "Cost centre key (FK to dim_cost_centre)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_cost_centre')
              field: cost_centre_key
      - name: vendor_key
        description: "Vendor key (FK to dim_vendor)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_vendor')
              field: vendor_key
      - name: product_key
        description: "Product key (FK to dim_product)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_key
      - name: currency_key
        description: "Currency key (simplified)"
        tests:
          - not_null
      - name: quantity
        description: "Order quantity"
        tests:
          - not_null
      - name: unit_price
        description: "Unit price in original currency"
        tests:
          - not_null
      - name: line_total_amount
        description: "Line total in original currency"
        tests:
          - not_null
      - name: line_total_aud
        description: "Line total converted to AUD"
      - name: line_total_usd
        description: "Line total converted to USD"
      - name: order_id
        description: "Order identifier"
        tests:
          - not_null
      - name: line_number
        description: "Line number within order"
        tests:
          - not_null

  - name: fct_data_quality
    description: "Data quality monitoring and exception tracking fact - Gold layer"
    columns:
      - name: data_quality_key
        description: "Surrogate key for data quality record"
        tests:
          - unique
          - not_null
      - name: date_key
        description: "Order date key (FK to dim_date)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: cost_centre_key
        description: "Cost centre key (FK to dim_cost_centre)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_cost_centre')
              field: cost_centre_key
      - name: vendor_key
        description: "Vendor key (FK to dim_vendor) - may be null for vendor exceptions"
        tests:
          - relationships:
              to: ref('dim_vendor')
              field: vendor_key
      - name: product_key
        description: "Product key (FK to dim_product) - may be null for SKU exceptions"
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_key
      - name: exception_count
        description: "Count of exceptions (always 1)"
        tests:
          - not_null
          - accepted_values:
              values: [1]
      - name: fuzz_score
        description: "Fuzzy matching score for SKU names"
      - name: vendor_fuzz_score
        description: "Fuzzy matching score for vendor names"
      - name: exception_type
        description: "Type of quality exception"
        tests:
          - not_null
          - accepted_values:
              values: ['SKU_NOT_IN_SEED', 'NAME_MISMATCH', 'VENDOR_MISMATCH', 'OTHER']

  - name: fct_price_variance
    description: "Price anomaly detection and variance analysis fact - Gold layer"
    columns:
      - name: price_variance_key
        description: "Surrogate key for price variance record"
        tests:
          - unique
          - not_null
      - name: date_key
        description: "Analysis date key (FK to dim_date)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: product_key
        description: "Product key (FK to dim_product)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_key
      - name: vendor_key
        description: "Vendor key (FK to dim_vendor)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_vendor')
              field: vendor_key
      - name: cost_centre_key
        description: "Cost centre key (FK to dim_cost_centre)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_cost_centre')
              field: cost_centre_key
      - name: avg_unit_price
        description: "Average unit price in USD"
        tests:
          - not_null
      - name: min_unit_price
        description: "Minimum unit price in USD"
        tests:
          - not_null
      - name: max_unit_price
        description: "Maximum unit price in USD"
        tests:
          - not_null
      - name: price_variance
        description: "Price variance measure"
      - name: order_count
        description: "Number of order lines in the variance calculation"
        tests:
          - not_null
      - name: total_quantity
        description: "Total quantity across all orders"
        tests:
          - not_null
      - name: has_significant_variance
        description: "Flag indicating significant price variance"
        tests:
          - not_null
          - accepted_values:
              values: [true]
