version: 2

models:
  - name: cur_sku_name_candidates
    description: "SKU-level name candidates for curation, showing each unique item description per SKU with occurrence count."
    columns:
      - name: sku_id
        description: "SKU identifier"
        tests:
          - not_null
      - name: item_description
        description: "Cleaned item description for this SKU."
        tests:
          - not_null
      - name: line_order_count
        description: "Number of times this description appears for this SKU."
        tests:
          - not_null
